//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultWPF.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Internships()
        {
            this.NecessarySkills = new HashSet<NecessarySkills>();
        }
    
        public int Id { get; set; }
        public int EmployerId { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public bool Ckosed { get; set; }
    
        public virtual Employers Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NecessarySkills> NecessarySkills { get; set; }
    }
}
