//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultWPF.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultDBEntities : DbContext
    {
        public DefaultDBEntities()
            : base("name=DefaultDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EducationalOrganizations> EducationalOrganizations { get; set; }
        public virtual DbSet<Employers> Employers { get; set; }
        public virtual DbSet<Internships> Internships { get; set; }
        public virtual DbSet<NecessarySkills> NecessarySkills { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Student_Skills> Student_Skills { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
