//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultWPF.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SpecializationId { get; set; }
        public int EOID { get; set; }
    
        public virtual EducationalOrganizations EducationalOrganizations { get; set; }
        public virtual Specializations Specializations { get; set; }
        public virtual Users Users { get; set; }
    }
}
